### ISSUE TITLE
ap75

### ISSUE THREAD

**Issue by zhu011** [httle/ARS-DETR#1]
Recently read your paper and benefited a lot, about the code part, how your ap75 is output

**Comment by yangxue0827** [comment]
Set `iou_thr=[0.5, 0.75]` when you want to return AP75 in validation.
https://github.com/httle/ARS-DETR/blob/4f4804baaa35aa6df5d5acbdef70426ca9883a18/mmrotate/datasets/dota.py#L182-L184

Besides, DOTA test evaluation server will also return the AP75.
