### ISSUE TITLE
About global batch size

### ISSUE THREAD

**Issue by misoyuri** [httle/ARS-DETR#17]
Hi, I read your good research work!
I found you set the mini-batch as 2 images per GPU.
How many GPUs did you use, or did you set the global batch?
If you were using 8 gpus, is the global batch size 16? Or did you train the model in a multi-node environment?

**Comment by httle** [comment]
We trained on 2 GPUs. 
If you use 8 GPUs, the global batch size will be 16, and you should also adjust the lr.
