### ISSUE TITLE
RDA Sampling Points

### ISSUE THREAD

**Issue by zjh21** [httle/ARS-DETR#4]
Thank you very much for your great work! I happened to discover the problem of the misalignment problem in Deformable Attention. Thus I am especially interested in the RDA method. As I visualized the sampling points using the your trained pth file (dn_arw_arm_arcsl_rdetr.pth), it appeared that the sampling points were aligned with the objects. However, the beautiful star shaped sampling points in Fig. 6 and Fig. 7 of your paper cannot be seen. I wonder what may have caused the problem. 

![图片](https://github.com/httle/ARS-DETR/assets/49853789/ee6b17a8-445c-4a3b-8f7f-98d3577698ff)

非常感谢精彩的工作。我恰好也发现过可变形注意力模块里面采样点和目标角度不对齐的问题，所以对RDA模块尤其感兴趣。我用您提供的pth文件可视化了采样点以后发现，采样点确实能随目标旋转而旋转，但论文中图6和图7米字形的采样点分布没有了。求教一下为何会有这样的情况

**Comment by httle** [comment]
图6和图7的那个米字型主要还是作为示意，实际的情况和你展示的这张图差不多，米字不会特别明显

**Comment by zjh21** [comment]
> 图6和图7的那个米字型主要还是作为示意，实际的情况和你展示的这张图差不多，米字不会特别明显

Thank you very much for your reply! I have no further questions.
谢谢回复！我了解了
