### ISSUE TITLE
mmrotate

### ISSUE THREAD

**Issue by renyccnu** [httle/ARS-DETR#5]
Hi,thanks for your excellent work.I was wondering when your work will be added to MMRotate1. x?Looking forward to seeing you work on mmarotate1.x.

**Comment by httle** [comment]
I think this job is not good enough to be included in mmrotate😂, but you can still use it for your own work.

**Comment by renyccnu** [comment]
您好，我想在DIOR-R数据集上复现您的ARS-DETR模型，但在测试时出现了错误，您可否提供关于DIOR-R数据集的配置文件？谢谢您的工作！




酒*醉逍遥
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "httle/ARS-DETR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月16日(星期一) 上午9:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [httle/ARS-DETR] mmrotate (Issue #5)





 
I think this job is not good enough to be included in mmrotate😂, but you can still use it for your own work.
